[features]
seeds = false
skip-lint = false

[programs.devnet]
dacl_bootstrap = "DaCLBooTStrap1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'no anchor tests yet'"
